// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jPFJP-BDdlrNuysnNTJKWiEfhwYTXfo',
    appId: '1:929046134968:android:8ae7d36a19e0c05bc8744d',
    messagingSenderId: '929046134968',
    projectId: 'taskify-1969',
    storageBucket: 'taskify-1969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6tco-owpSj5QH5K49ZklzGDpXMfnNB9Q',
    appId: '1:929046134968:ios:f6ff8bad848d5949c8744d',
    messagingSenderId: '929046134968',
    projectId: 'taskify-1969',
    storageBucket: 'taskify-1969.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6tco-owpSj5QH5K49ZklzGDpXMfnNB9Q',
    appId: '1:929046134968:ios:f6ff8bad848d5949c8744d',
    messagingSenderId: '929046134968',
    projectId: 'taskify-1969',
    storageBucket: 'taskify-1969.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAwis_cnXVpWIMrNzvWAcaOhPVrIJSewE',
    appId: '1:929046134968:web:e7134eb8fd89ed46c8744d',
    messagingSenderId: '929046134968',
    projectId: 'taskify-1969',
    authDomain: 'taskify-1969.firebaseapp.com',
    storageBucket: 'taskify-1969.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAwis_cnXVpWIMrNzvWAcaOhPVrIJSewE',
    appId: '1:929046134968:web:5f2754f3d7efee5bc8744d',
    messagingSenderId: '929046134968',
    projectId: 'taskify-1969',
    authDomain: 'taskify-1969.firebaseapp.com',
    storageBucket: 'taskify-1969.firebasestorage.app',
  );

}